Repository chaos-mesh/chaosd, pull requests merged in 2022-06, with the labels that each got.

#173 stress attack: ignore error when stress-ng process is not exists
  pkg/server/chaosd/stress.go
Labels: status/LGT2, status/can-merge, size/XS

#172 Add flag `redis-path` to sentinel restart
  cmd/attack/redis.go
Labels: status/LGT2, status/can-merge, size/XS

#163 redisChaos: add cache limit
  cmd/attack/redis.go
  pkg/core/redis.go
  pkg/server/chaosd/redis.go
Labels: size/M, status/LGT2, status/can-merge

#165 support HTTP Attack on chaosd
  cmd/attack/attack.go
  cmd/attack/http.go
  pkg/core/experiment.go
  pkg/core/http.go
  pkg/server/chaosd/http.go
  pkg/server/chaosd/recover.go
  pkg/server/httpserver/server.go
Labels: status/LGT1, size/XL

#175 RadisChaos: Add Cache Expiration
  cmd/attack/redis.go
  pkg/core/redis.go
  pkg/server/chaosd/redis.go
Labels: size/L, status/LGT2, status/can-merge

#170 support user defined attack
  cmd/attack/attack.go
  cmd/attack/user_defined.go
  pkg/core/experiment.go
  pkg/core/user_defined.go
  pkg/server/chaosd/recover.go
  pkg/server/chaosd/user_defined.go
  pkg/server/httpserver/server.go
  test/integration_test/user_defined/run.sh
Labels: status/LGT2, status/can-merge, size/XL
