Repository chaos-mesh/chaosd, pull requests merged in 2022-03, with the labels that each got.

#130 Network: support down NIC
  cmd/attack/network.go
  pkg/core/network.go
  pkg/server/chaosd/network.go
  test/integration_test/network/run.sh
Labels: size/L, status/LGT2, status/can-merge

#135 Makefile: support build and download releated tools
  .github/workflows/release_latest.yml
  .github/workflows/release_tag.yml
  Makefile
  README.md
Labels: status/LGT2, status/can-merge, size/XL

#140 chore: update help information for recover-cmd
  cmd/attack/process.go
Labels: status/LGT2, status/can-merge, size/XS

#139 support auto completion
  cmd/completion/completion.go
  cmd/main.go
  cmd/recover/completion.go
  cmd/recover/recover.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XL

#145 ignore process not found while recovering the stress
  pkg/server/chaosd/stress.go
Labels: status/LGT2, status/can-merge, size/XS
