Repository chaos-mesh/chaosd, pull requests merged in 2022-08, with the labels that each got.

#194 Add `Type` to `IPSet`
  pkg/core/network.go
Labels: status/LGT1, size/XS

#195 Add flag `accept-tcp-flag` to network delay
  cmd/attack/network.go
  pkg/core/network.go
  pkg/core/network_test.go
  pkg/server/chaosd/network.go
Labels: size/M, status/LGT2, status/can-merge

#198 download memStress and stress-ng according to the architecture
  Makefile
Labels: status/LGT2, status/can-merge, size/S

#202 Make byteman plugins runnable on jdk8
  Makefile
  test/integration_test/jvm/run.sh
Labels: status/LGT2, status/can-merge, size/XS

#204 update chaos-mesh pkg to latest
  go.mod
  go.sum
Labels: status/LGT1, size/XS

#205 Fix: gitVersion is invalid when executing `chaosd version`
  hack/version.sh
Labels: status/LGT2, status/can-merge, size/S

#201 add arm64 master build
  .github/workflows/release_latest.yml
Labels: status/LGT2, status/can-merge, size/S

#206 upgrade byteman-helper to v4.0.18-0.11
  Makefile
  test/integration_test/jvm/run.sh
Labels: status/LGT2, status/can-merge, size/XS

#209 Fix some minor bugs
  .github/workflows/release_latest.yml
  .github/workflows/release_tag.yml
  Makefile
  test/integration_test/jvm/run.sh
Labels: size/S

#211 Fix wrong gitVersion info and github action failed on arm
  .github/workflows/release_latest.yml
  .github/workflows/release_tag.yml
Labels: size/M, status/LGT2, status/can-merge
