Repository chaos-mesh/chaosd, pull requests merged in 2022-09, with the labels that each got.

#214 Fix partition not work
  cmd/attack/network.go
  pkg/core/network.go
Labels: status/LGT1, size/XS, bug-fix

#215 Store iptables when creating network attack
  pkg/core/network.go
  pkg/core/network_test.go
  pkg/server/chaosd/network.go
Labels: size/L, status/LGT1

#217 Rename `FillByFAllocate` to `FillByFallocate`
  cmd/attack/disk.go
  pkg/core/disk.go
Labels: status/LGT1, size/S
