Repository chaos-mesh/chaosd, pull requests merged in 2022-07, with the labels that each got.

#182 minor fix BUG in http chaos config action
  pkg/core/http.go
Labels: status/LGT1, size/XS

#177 HTTP attack: support send HTTP request
  cmd/attack/http.go
  pkg/core/http.go
  pkg/server/chaosd/http.go
Labels: size/L, status/LGT1

#181 kafka attack: fill action support change retention bytes
  cmd/attack/kafka.go
  pkg/core/kafka.go
  pkg/server/chaosd/kafka.go
Labels: size/L, status/LGT2, status/can-merge

#174 network: generate network traffic by using iperf
  cmd/attack/network.go
  pkg/core/network.go
  pkg/server/chaosd/network.go
Labels: size/L, status/LGT2, status/can-merge

#184 Merge update into main
  .github/workflows/ci.yml
  .github/workflows/release_latest.yml
  .github/workflows/release_tag.yml
  Makefile
  cmd/attack/attack.go
  cmd/attack/http.go
  go.mod
  go.sum
  pkg/core/experiment.go
  pkg/core/http.go
  pkg/core/network.go
  pkg/crclient/client.go
  pkg/server/chaosd/clock_amd64.go
  pkg/server/chaosd/host_unix.go
  pkg/server/chaosd/http.go
  pkg/server/chaosd/network.go
  pkg/server/chaosd/recover.go
  pkg/server/chaosd/stress.go
  pkg/server/httpserver/server.go
  pkg/server/server.go
  test/integration_test/stress/run.sh
Labels: status/LGT2, status/can-merge, size/XXL

#188 Add json tag for kafka attack
  pkg/core/kafka.go
  pkg/core/redis.go
Labels: size/M, status/LGT2, status/can-merge

#189 Use shirou/gopsutils to get process full name
  go.mod
  go.sum
  pkg/server/chaosd/process.go
Labels: status/LGT2, status/can-merge, size/S

#192 Add device to ToTc()
  pkg/core/network.go
Labels: status/LGT2, status/can-merge, size/XS
