Repository chaos-mesh/chaosd, pull requests merged in 2022-04, with the labels that each got.

#136 support "both" direction for network partition
  cmd/attack/network.go
  pkg/core/network.go
  pkg/core/network_test.go
Labels: enhancement, size/L, status/LGT2, status/can-merge

#153 JVM attack: minor fix on memory
  pkg/server/chaosd/jvm.go
  pkg/server/chaosd/jvm_test.go
  pkg/utils/env.go
Labels: status/LGT2, status/can-merge, size/XS

#155 bump gopsutil to 3.21.11
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S

#123 support file attack
  Makefile
  cmd/attack/attack.go
  cmd/attack/file.go
  pkg/core/experiment.go
  pkg/core/file.go
  pkg/server/chaosd/file.go
  pkg/server/chaosd/recover.go
  pkg/utils/env.go
  pkg/utils/util.go
  test/integration_test/file/run.sh
  tools/file/append.go
  tools/file/copy.go
  tools/file/create.go
  tools/file/delete.go
  tools/file/file.go
  tools/file/go.mod
  tools/file/go.sum
  tools/file/modify.go
  tools/file/rename.go
  tools/file/replace.go
Labels: enhancement, status/LGT2, status/can-merge, size/XXL

#157 JVM attack: add json label for MySQL config
  cmd/attack/attack.go
  pkg/core/jvm.go
Labels: status/LGT2, status/can-merge, size/S
