Repository chaos-mesh/chaosd, pull requests merged in 2022-05, with the labels that each got.

#152 redisChaos: support sentinel stop/restart
  cmd/attack/attack.go
  cmd/attack/redis.go
  go.mod
  go.sum
  pkg/core/experiment.go
  pkg/core/redis.go
  pkg/server/chaosd/recover.go
  pkg/server/chaosd/redis.go
  pkg/server/httpserver/server.go
  pkg/swaggerserver/empty_handler.go
  pkg/swaggerserver/swagger_handler.go
Labels: status/LGT2, status/can-merge, size/XL

#161 Update chaos-mesh version to 20220511035234-10df92fcde77.
  .github/workflows/ci.yml
  .github/workflows/release_latest.yml
  .github/workflows/release_tag.yml
  Makefile
  go.mod
  go.sum
  pkg/crclient/client.go
  pkg/server/chaosd/clock_amd64.go
  pkg/server/chaosd/host_unix.go
  pkg/server/chaosd/network.go
  pkg/server/chaosd/stress.go
  pkg/server/server.go
Labels: size/XXL

#168 add ci test on arm
  .github/workflows/ci.yml
  test/integration_test/jvm/run.sh
  test/integration_test/run.sh
Labels: status/LGT2, status/can-merge, size/S

#158 support vm attack
  cmd/attack/attack.go
  cmd/attack/clock.go
  cmd/attack/vm.go
  pkg/core/clock.go
  pkg/core/experiment.go
  pkg/core/vm.go
  pkg/server/chaosd/recover.go
  pkg/server/chaosd/vm.go
  pkg/server/httpserver/server.go
Labels: size/L, status/LGT2, status/can-merge, docs/require-changes

#154 implement kafka chaos
  cmd/attack/attack.go
  cmd/attack/kafka.go
  go.mod
  go.sum
  pkg/core/experiment.go
  pkg/core/kafka.go
  pkg/server/chaosd/kafka.go
  pkg/server/chaosd/kafka_test.go
  pkg/server/chaosd/recover.go
  pkg/server/httpserver/server.go
Labels: status/LGT2, status/can-merge, size/XXL, docs/require-changes

#159 Support Redis cache penetration
  cmd/attack/redis.go
  pkg/core/redis.go
  pkg/server/chaosd/redis.go
Labels: size/M, status/LGT2, status/can-merge
